using System.Runtime.InteropServices;

namespace Legio.Protocol;

/// <summary>
/// Tessera (The Tablet/Tile).
/// A compact performance report generated by the Trecenarius after a job cycle.
/// This struct is BLITTABLE - it can be passed directly to F# or GPU without marshaling.
/// </summary>
[StructLayout(LayoutKind.Sequential, Pack = 4)] // 4-byte packing for broad compatibility
public struct Tessera
{
    /// <summary>
    /// Total duration of the task in high-frequency ticks.
    /// </summary>
    public long DurationTicks;

    /// <summary>
    /// Number of items processed in this batch.
    /// </summary>
    public int ItemCount;

    /// <summary>
    /// ID of the Centurion (Thread) that performed the work.
    /// Useful for tracking thread-specific performance anomalies (e.g., E-Cores).
    /// </summary>
    public int CenturioId;

    /// <summary>
    /// ID of the Cohort (System) reporting.
    /// </summary>
    public int CohortId;

    /// <summary>
    /// The current CPU pressure (0.0 - 1.0) observed during execution.
    /// </summary>
    public float CpuPressure;
}